version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: harmalh-hermes-workspace_workspace_1
      APP_PORT: 3000

  workspace:
    image: ghcr.io/harmalh/hermes-workspace-ui-umbrel:0.1.3@sha256:c256942f50c2ca259b6e45b1ed39edc143a7a39fb14c4be6afe54c14ebc6f04f
    restart: on-failure
    init: true
    depends_on: [hermes-api]
    environment:
      NODE_ENV: "production"
      HERMES_API_URL: "http://hermes-api:8642"

  hermes-api:
    image: ghcr.io/harmalh/hermes-workspace-api-umbrel:0.1.3@sha256:52fcae1ab8fd2605eb33decf42192e339bbe6bd6587875366b9854788a501554
    restart: on-failure
    init: true
    stop_grace_period: 1m
    environment:
      API_SERVER_ENABLED: "true"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_PORT: "8642"
      HOME: /opt/hermes-home
    volumes:
      - ${APP_DATA_DIR}/hermes:/opt/hermes-home
